oeqa: Replace librdfa with alisp as testcase for devtool add
librdfa codebase is 10+ year old and is starting to show cracks
with gcc-14 e.g. it fails to compile

 ../../../../../../workspace/sources/librdfa/c/rdfa.c:345:36: error: passing argument 2 of 'rdfa_next_mapping' from incompatible pointer type [-Wincompatible-pointer-types]
|          rdfa_next_mapping(umap++, &umap_key, &umap_value);
|                                    ^~~~~~~~~
|                                    |
|                                    const char **

Replace with alisp gnu project which is also autotools based but the
codebase is maitained well.

(From OE-Core rev: 1aeebe9b01b665bbb485b3ca401067dd3ebd8a96)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>